[project]
name = "langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-openai>=0.3.7",
    "langchain-upstage>=0.6.0",
    "pip>=25.0.1",
    "python-dotenv>=1.0.1",
]
